version: "3"
services:
  sra-taxii2-server:
    container_name: sra-taxii2-server
    build: 
      context: ./
    depends_on: 
      - sra-taxii2-mongo
    restart: always
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
      - /opt/taxii/certs:/opt/taxii/certs
      - /opt/taxii/filetemp:/opt/taxii/filetemp
    ports:
      - "3002:3000"
      - "3003:3001"
    networks:
      - taxii_bridge
    dns: 8.8.8.8

  sra-taxii2-manager-server:
    container_name: sra-taxii2-manager-server
    build: 
      context: ../sra-taxii2-manager/server
    depends_on: 
      - sra-taxii2-mongo
    restart: always
    volumes:
      - ../sra-taxii2-manager/server:/usr/src/app/
      - /usr/src/app/node_modules
      - /opt/taxii/certs:/opt/taxii/certs
    ports:
      - "4002:4000"
      - "4003:4001"
    networks:
      - taxii_bridge
    dns: 8.8.8.8

  sra-taxii2-mongo:
    container_name: sra-taxii2-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27019:27017"
    networks:
      - taxii_bridge
    dns: 8.8.8.8
  
  sra-taxii2-redis:
    container_name: sra-taxii2-redis
    image: redis
    volumes:
      - ./redisData:/data
    ports: 
      - "6500:6379"
    networks:
      - taxii_bridge
    dns: 8.8.8.8
  
  sra-taxii2-server-queue:
    container_name: sra-taxii2-server-queue
    build:
      context: ../sra-taxii2-server-queue
    depends_on:
      - sra-taxii2-redis
      - sra-taxii2-server
    restart: always
    volumes:
      - ../sra-taxii2-server-queue:/usr/src/app/
      - /usr/src/app/node_modules
      - /opt/taxii/filetemp:/opt/taxii/filetemp
    networks:
      - taxii_bridge
    dns: 8.8.8.8

networks:
  taxii_bridge: 
    ipam:
      driver: default
      config:
       - subnet: 10.0.24.0/24

